### ISSUE TITLE
Git LFS v1.1.2

### ISSUE THREAD

**Issue by technoweenie** [github/git-lfs#1029]
* [x] Base64 issues with `?` #989 (@technoweenie)
* [x] fix zombie git proc issue #1012 (@rlaakkol)
* [x] fix problems with files containing unicode characters #1016 (@technoweenie)
* [x] fix panic in `git cat-file` parser #1006 (@technoweenie)
* [x] display error messages in non-fatal errors #1028 #1039 #1042 (@technoweenie)
* [x] fix concurrent map access in progress meter (@technoweenie)
