### ISSUE TITLE
Release v1.3

### ISSUE THREAD

**Issue by technoweenie** [github/git-lfs#1354]
I think we can release v1.3 pretty next week. Here are a few small things I'd like to take care of. @sinbad: is the transfer queue in a good place, or do you have more updates you want for v1.3? 

* [x] WIP transferqueue race fix #1255
* [x] Fix bug in Windows installer under Win32. #1200
* [x] Use proxy from git config if available ~~#1173~~ #1358 
* [x] Change to the git-lfs meta package for Chocolatey #1146
* [x] custom transfer adapter #1367 
* [x] clarify batch api response spec #1368 #1371
* [x] fix / improve submodule handling in `git lfs clone` with git 2.9+ #1373 
* [x] windows fixes #1374

**Comment by technoweenie** [comment]
Sounds good, I added it to the list.

**Comment by sinbad** [comment]
Custom transfers are ready: #1367

**Comment by sinbad** [comment]
There's a bunch of failures on Windows that need fixing, I'm taking a look this afternoon.

**Comment by technoweenie** [comment]
I'd like to :ship: this tomorrow morning. The only things we're waiting on are the transfer key PR (#1389), and of course the release notes (#1388). Any objections to merging those and shipping?

**Comment by sinbad** [comment]
Happy with 🚢 provided those last docs & tests are tweaked in #1389.
