### ISSUE TITLE
config-next: Tracking Issue

### ISSUE THREAD

**Issue by ttaylorr** [github/git-lfs#1425]
This is a tracking issue to keep tabs on the `config-next` refactoring.

The broad goals of this refactoring are to move away from the domain-specific API that package `config` currently exposes, to a data-fetching type, and a series of well-factored types and packages throughout the rest of LFS.

Specifically, this refactoring comes in a number of parts:

- [x] Introduce `Fetcher`, implement `EnvFetcher`, and integrate with `*config.Config`.
- [x] Update tests to not use mutable behavior like `Set` and `SetAll`.
- [x] Refactor `Fetcher` type as described in https://github.com/github/git-lfs/commit/e32fabe37fc150b21a5d2d7594a5300c1388c5cb.
- [x] Implement the `GitFetcher`.
- [ ] Remove mutable `.gitconfig`-related operations
- [ ]  Piece by piece, remove legacy calls to `GetenvBool`, replacing them with `.Env.Bool` (and etc).
- [ ] Piece by piece, remove domain knowledge from the `*config.Config` type, in favor of the methodology described in https://github.com/github/git-lfs/pull/1390#issuecomment-236068550.

**Comment by ttaylorr** [comment]
Acking for internal script

**Comment by ttaylorr** [comment]
Acking for internal script.

**Comment by ttaylorr** [comment]
> Piece by piece, remove domain knowledge from the `*config.Config` type, in favor of the methodology described in https://github.com/github/git-lfs/pull/1390#issuecomment-236068550.

Taking this one off of the tracking issue, since this is now outside the scope of the `config-next` refactoring. As discussed with @technoweenie, a good first step would be to outline all of the places the `config` package is used irresponsibly from `api`.

**Comment by ttaylorr** [comment]
Woo-hoo! 🎉
