### ISSUE TITLE
Release v0.5.2

### ISSUE THREAD

**Issue by technoweenie** [github/git-lfs#281]
## DONE

* [x] Add experimental support for batch API calls #285 (@rubyist)
* [x] Add `git lfs fetch` command for downloading objects. #285 (@rubyist)
* [x] Fix `git lfs track` issues when run outside of a git repository #200, #312
* [x] Fix `git lfs track` for paths with spaces in them #327
* [x] Fix bug with zero length files #346 (@technoweenie)
* [x] The Git `pre-push` warns if `git-lfs` is not installed #339 (@rubyist)
* [x] Fix Content-Type header #329 (@joerg)
* [x] Trace performance in case of error while scanning refs #311 (@michael-k)
* [x] Improve build linux build instructions #299 (@jsh)
* [x] Various coding convention cleanups #300 (@michael-k)
* [x] Error handling refactoring #305 (@michael-k)
* [x] Performance tracing improvements #311 (@michael-k)
* [x] Fix detection of `LocalGitDir` and `LocalWorkingDir` #312 #354 #361 (@michael-k)
* [x] New integration test suite #306 (@technoweenie)
* [x] Prevent tracking a file outside of the git repository #294 (@Aorjoa)
* [x] Add script for building debian package #309 (@ssgelm)
* [x] Fix bug that prevented tracking files with spaces in the name. #327 (@technoweenie)
* [x] Fix charset parameter in Content-Type header #329 (@joerg)
* [x] Move to nut for dependency management. #331 (@technoweenie)
* [x] Fix `pre-push` hook so it doesn't exit with an error if `git lfs` does not exist. #339 (@rubyist)
* [x] Fix bug that prevented zero length files from being managed by Git LFS #346 (@technoweenie)
* [x] Fix inconsistent file mode bits for directories created by Git LFS #364 (@michael-k)
* [x] Simple optimization to the clean and smudge filters #377 (@bozaro)
* [x] Fix bug in `git lfs untrack` that incorrectly some removed entries from `.gitattributes` #398 (@michael-k)
* [x] Batch API improvements #358 (@rubyist)
* [x] Resolved race condition #396 (@michael-k)
* [x] Cleaned up arguments #392 (@michael-k)
* [x] Don't read configuration from nonexistent file #391 (@bozaro)
* [x] Do not defer close in loop #384 (@michael-k)
* [x] Collect HTTP transfer stats #366, #400 (@rubyist)
* [x] Fixed tracking issues #356 (@michael-k)
* [x] Support GIT_DIR and GIT_WORK_TREE #370 (@michael-k)
* [x] Hide Git application window in Windows #381 (@bozaro)
* [x] Remove Git version from Git LFS version string #382 (@bozaro)
* [x] Enforce relative paths in `git lfs track` #356 (@michael-k)
* [x] Scripts for building package on CentOS #313 #332 (@andyneff)
* [x] Add `git lfs fsck` #373 (@zeroshirts, @michael-k)
* [x] Add support for configured URLs containing credentials per RFC1738 #408 (@ewbankkit)

**Comment by michael-k** [comment]
#290 is missing at “Add `git lfs fsck`”.

**Comment by technoweenie** [comment]
Ah thanks, the PR changed.

**Comment by technoweenie** [comment]
Wow, there's a lot of stuff in here.  I think it's (way past) time to release Git LFS v0.5.2. I think there are a few really small patches that we can apply. But bigger things can wait for v0.5.3.

**Comment by jsh** [comment]
Rick,

I agree, however FWIW, I tried to build it on CentOS this morning and the
script I wrote will no longer work. Looks like you've updated the bootstrap
script in a way that breaks it.

I've been too insanely busy to pay attention. Mea culpa.

On Thu, Jun 11, 2015 at 2:53 PM, risk danger olson <notifications@github.com
> wrote:

> Wow, there's a lot of stuff in here. I think it's (way past) time to
> release Git LFS v0.5.2. I think there are a few really small patches that
> we can apply. But bigger things can wait for v0.5.3.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/github/git-lfs/issues/281#issuecomment-111274830>.
>



-- 
Jeffrey Haemer <jeffrey.haemer@gmail.com>
720-837-8908 [cell], http://seejeffrun.blogspot.com [blog],
http://www.youtube.com/user/goyishekop [vlog]
*פרייהייט? דאס איז יאַנג דינען וואָרט.*

**Comment by technoweenie** [comment]
I tried to change things to be easier for Windows development, but ended up breaking things if you don't know how to install a Go package properly. I'm trying to find a good balance of playing well with Go devs, while not alienating everyone else.

@andyneff has been working on an install and an rpm package script for CentOS though.

**Comment by jsh** [comment]
Cool. Me too. Or at least I was last week. :-(

I should send him my specfile -- let him make fun of it.

On Thu, Jun 11, 2015 at 3:28 PM, risk danger olson <notifications@github.com
> wrote:

> I tried to change things to be easier for Windows development, but ended
> up breaking things if you don't know how to install a Go package properly.
> I'm trying to find a good balance of playing well with Go devs, while not
> alienating everyone else.
>
> @andyneff <https://github.com/andyneff> has been working on an install
> and an rpm package script for CentOS though.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/github/git-lfs/issues/281#issuecomment-111282387>.
>



-- 
Jeffrey Haemer <jeffrey.haemer@gmail.com>
720-837-8908 [cell], http://seejeffrun.blogspot.com [blog],
http://www.youtube.com/user/goyishekop [vlog]
*פרייהייט? דאס איז יאַנג דינען וואָרט.*

**Comment by technoweenie** [comment]
I'm referring specifically to #313 and #332. Have you checked them out? It sounds like they're ready to be merged.

**Comment by ssgelm** [comment]
The deb script is broken as well.  I will try to fix it tonight though!

**Comment by andyneff** [comment]
@jsh Last I checked 13 days ago, #313 was working as expected in CentOS 5, 6, and 7.

@technoweenie I haven't tried any windows build (yet), so I may not know what I'm talking about, but I can only imagine if you are talking about on windows we can't do "symlinks" to fake the GOPATH, will using junctions instead make windows happy?

**Comment by technoweenie** [comment]
@andyneff: The current `script/bootstrap` doesn't use symlinks anymore. That's why you had to wrestle with `$GOPATH` a bit a week ago.

There are a few issues with the scripts (`script/fmt` and `script/bootstrap`) themselves not running on Windows due to shell errors. But it builds now with `go get` and `go install` if you know how Go packages work. I need to write up a guide for any Go newbs.

**Comment by michael-k** [comment]
Please add **Review man pages** to the todo list.  At least [git-lfs-logs.1.ronn](https://github.com/github/git-lfs/blob/296dddf704e44bdee89b2e16c6d76078e197cf8f/docs/man/git-lfs-logs.1.ronn) is out of date.

**Comment by michael-k** [comment]
*Enforce relative paths in `git lfs track` #230* has been fixed in #356

**Comment by technoweenie** [comment]
Thanks, I just added those to the list.

**Comment by technoweenie** [comment]
Updated the changelog in https://github.com/github/git-lfs/pull/420. I focused on the user-visible changes to the tools, and left out refactoring PRs (sorry @michael-k).

**Comment by michael-k** [comment]
Totally fine with me.

**Comment by technoweenie** [comment]
Just shipped Git LFS v0.5.2. We're going to try something a bit different with the next push:

* Git LFS v0.6.0 has a planning issue #426
* Git LFS v0.5.3 will be released from the `stable-0.5` branch so we can ship multiple v0.5.x releases while taking our time on v0.6.#425

Thanks to everyone that pitched in on v0.5.2 :metal:
