### ISSUE TITLE
Roadmap: Fast, efficient uploading and downloading

### ISSUE THREAD

**Issue by technoweenie** [github/git-lfs#414]
This is a meta issue for the roadmap. Comments should be geared towards the addition and deletion of tasks. Leave detailed discussion to issues linked in tasks. If a task doesn't have an issue next to it, create one and leave a comment here so we can update the list.

* [x] Batch API (experimental in v0.5.2+, stable by v0.6.x)
* [x] Batch API: 401 responses #415
* [x] Batch API: upper limit of the number of objects per batch #419 #476
* [x] Batch API: define semantics for partial failures #417
* [x] Support chunked Transfer-Encoding #385
* [x] SSH auth: stop sending OID for batch requests #416
* [ ] Use `post-checkout` for downloads #616
* [x] Resumable downloads
* [x] Resumable uploads

## Ideas

* [ ] Chunked uploads
* [ ] Binary diffing
* [ ] Bulk tarball uploads or downloads through the storage API.

**Comment by bozaro** [comment]
I think, the good idea for batch API is removing ```{oid}``` from ```git-lfs-authenticate``` command:
```
ssh git@github.com git-lfs-authenticate user/repo.git download {oid}
```
The presence of this argument needs to perform this command for each object is sent.

**Comment by technoweenie** [comment]
@bozaro: Good point. We'll definitely make that change for the batch api.
