### ISSUE TITLE
Release v0.5.3

### ISSUE THREAD

**Issue by technoweenie** [github/git-lfs#425]
Git LFS v0.5.3 will be an incremental upgrade from 0.5.2. Backported patches need to be applied to the `release-0.5` branch.

## TODO

* [x] `git lfs fetch` bugs #429 (@rubyist)
* [x] Push can crash on 32 bit architectures #450 (@rubyist)
* [x] Improved SSH support #404, #464 (@sinbad, @technoweenie)
* [x] support 307 redirects with relative url #442 (@sinbad)
* [x] Fix `init` issues when upgrading #446 #451 #452 #465 (@technoweenie, @rubyist)
* [x] Support chunked Transfer-Encoding #386 (@ryansimmen)
* [x] Fix issue with pushing deleted objects #461 (@technoweenie)
* [x] Teach `git lfs push` how to send specific objects #449 (@larsxschneider)
* [x] Update error message when attempting to push objects that don't exist in `.git/lfs/objects` #447 (@technoweenie)
* [x] Fix bug in HTTP client when response body is nil #472 #488 (@rubyist, @technoweenie)
* [x] `-crlf` flag in gitattributes is deprecated #475 (@technoweenie)

**Comment by technoweenie** [comment]
@rubyist: Do you think there have been any changes merged to master that would break v0.5.3 compatibility? I believe it's still using the old API unless the `lfs.batch` setting is enabled. I'd like to just release v0.5.3 from there.

**Comment by rubyist** [comment]
I don't think so, all the batch work should still be behind the `lfs.batch` switch.

**Comment by technoweenie** [comment]
Cool. I'm going to line the troops up for a QA run tomorrow.

**Comment by technoweenie** [comment]
Ah, I found something. I think master is treating 403 as a fatal error:

```
# v0.5.3 
$ GIT_SSL_NO_VERIFY=1 git push   
remote: Invalid username or password.
fatal: Authentication failed for 'https://172.28.128.4/ghe-admin/git-lfs-qa/'

# v0.5.2
$ GIT_SSL_NO_VERIFY=1 git push
Username for 'https://172.28.128.4': ghe-admin
Password for 'https://ghe-admin@172.28.128.4': 
```

I think that's enough that I should go off the `release-0.5` branch.

**Comment by technoweenie** [comment]
I used the backport script and pulled over as much of [these commits between `release-0.5` and `master`](https://github.com/github/git-lfs/compare/github:b351a8b...github:67b9cf0). I left out these two PRs that deal with the 401/403 changes for the batch API:

* https://github.com/github/git-lfs/pull/415
* https://github.com/github/git-lfs/pull/468

If there's something easy that we can do on master to keep the old 403 behavior on the legacy API, I'll be happy to cut v0.5.3 from master. But, the changes actually listed in this issue were all backported with just 1 conflict in `.gitignore`.

**Comment by technoweenie** [comment]
Okay, spoke too soon.  Here's the behavior with the current `release-0.5` branch:

```
$ GIT_SSL_NO_VERIFY=1 git push origin master   
remote: Invalid username or password.
fatal: Authentication failed for 'https://172.28.128.4/ghe-admin/git-lfs-qa/'

$ GIT_SSL_NO_VERIFY=1 git push origin master
Username for 'https://172.28.128.4': ghe-admin 
Password for 'https://ghe-admin@172.28.128.4': 
(5 of 5 files) 5.21 MB 9s                                                                                                                                                                                                                                                                                                                                                   
Counting objects: 8, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (8/8), done.
Writing objects: 100% (8/8), 1.00 KiB | 0 bytes/s, done.
Total 8 (delta 1), reused 0 (delta 0)
To https://172.28.128.4/ghe-admin/git-lfs-qa
   5e90f36..1bc7c14  master -> master
```

So apparently I backported this behavior change somewhere too. Then, I tried it with the current master:

```
$ GIT_SSL_NO_VERIFY=1 git push origin master
remote: Invalid username or password.
fatal: Authentication failed for 'https://172.28.128.4/ghe-admin/git-lfs-qa/'

$ GIT_SSL_NO_VERIFY=1 git push origin master
Username for 'https://172.28.128.4': ghe-admin
Password for 'https://ghe-admin@172.28.128.4': 
remote: Invalid username or password.
fatal: Authentication failed for 'https://172.28.128.4/ghe-admin/git-lfs-qa/'

$ GIT_SSL_NO_VERIFY=1 git push origin master
Username for 'https://172.28.128.4': ghe-admin
Password for 'https://ghe-admin@172.28.128.4': 
(5 of 5 files) 5.96 MB 9s                                                                                                                                                                                                                                                                                                                                                   
Counting objects: 9, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (9/9), done.
Writing objects: 100% (9/9), 1.08 KiB | 0 bytes/s, done.
Total 9 (delta 2), reused 0 (delta 0)
To https://172.28.128.4/ghe-admin/git-lfs-qa
   1bc7c14..63047ed  master -> master
```

Same thing.  Then, I tried with the actual v0.5.2 release.  **SAME THING** I think my previous experience was a result of the git credential helper changing in between `git push` calls, and not because I was swapping `git-lfs` binaries.

**Comment by technoweenie** [comment]
Just shipped Git LFS v0.5.3: https://github.com/github/git-lfs/releases/tag/v0.5.3

/cc @github/desktop

**Comment by robrix** [comment]
Opened issues against @github/mac and @github/windows :sparkles:

Thanks @technoweenie!
