### ISSUE TITLE
Release v0.6.0

### ISSUE THREAD

**Issue by technoweenie** [github/git-lfs#426]
Git LFS v0.6.0 will be a larger update using a finalized Batch API. Any smaller changes should also be applied to the `release-0.5` branch to be included in a v0.5.x point release.

## TODO

* [x] Rename `git lfs fetch` to `git lfs pull` #527 (@sinbad)
* [x] Add new `git lfs fetch` for downloading to the local `.git/lfs/objects` storage. #527 (@sinbad)
* [x] Add new `git lfs checkout` for replacing LFS pointers in the working directory from the local storage. #527 (@sinbad)
* [x] Support using credentials from multiple accounts #554 (@clareliguori)
* [x] Finalize Batch API #415 #417 #419
* [ ] Honor netrc #171
* [ ] Fix issue with ssh shorthands #278 
* [x] Extensions #486 #525
* [ ] Dynamic size cutoff for blob scanning #524 
* [x] Failures during a checkout can leave the git index locked #558
* [ ] git-lfs staged but unstaged changes with 0B tracked file #557 
* [x] Don't attempt to upload old files when pushing new branches #564

## Investigate

* [ ] Detect when credential cacher is not setup #523

**Comment by Leviathan1753** [comment]
Looking forward to this release.  Pushing new branches is extremely painful right now.

**Comment by bozaro** [comment]
Is there any estimated release date of version 0.6.0?

**Comment by technoweenie** [comment]
This week! Anxious for you to take a crack at the new windows installer :)

**Comment by technoweenie** [comment]
Git LFS v0.6.0 is out now. I created #653 to start tracking the next release.

**Comment by Leviathan1753** [comment]
Hey all!  Thanks for the v6.0 release.  Many of the showstopper bugs seem to have been squashed.

One question, though:
Listed here as done is the Batch API + new fetch setups.  Is that the new "zipped" up bulk download systems?  When doing a fresh clone/Checkout, my gitlfs still seems to be HTTP requesting single files in snail-speed fashion.

**Comment by technoweenie** [comment]
The Batch API was implemented, reducing the LFS API calls to 1%. But the actual large file downloading is the same, unfortunately. The "zipped up bulk download" stuff is just an idea, still. Sounds neat on paper, but it can potentially be complicated on the server side. Have you tried bumping the `lfs.concurrenttransfers` config value up? 

https://github.com/github/git-lfs/blob/master/docs/man/git-lfs-config.5.ronn

You can do that on any local repository:

```bash
# applies only to the current repository
$ git config lfs.concurrenttransfers 5

# applies to all of your repositories
$ git config --global lfs.concurrenttransfers 5
```

**Comment by Leviathan1753** [comment]
Ah, so it's still doing single HTTP requests for each file, just concurrently?  I did notice the downloads still took a long time, even for small files.  I imagine it's the overhead of starting/doing an HTTP request per file?   My recent clone took a few hours for ~2500 files taking about 4-5GB.   I suppose that might make sense if the amazon servers are giving me the large files slowly, and the small ones also take long due to the HTTP request overhead?

I'll try the concurrent setting and do another clone for fun and see what happens.
Thanks!

**Comment by technoweenie** [comment]
Oh yeah, for downloads we're limited by Git's smudge filters. Details here: https://github.com/github/git-lfs/issues/616

Long story short, we won't have a good solution right now other than essentially giving you the option to disable git smudging, and forcing you to type `git lfs pull`.

**Comment by Leviathan1753** [comment]
Ah, that makes sense.  Thanks!
