### ISSUE TITLE
Roadmap: Improved installation/upgrade experience

### ISSUE THREAD

**Issue by technoweenie** [github/git-lfs#531]
This is a meta issue for the roadmap. Comments should be geared towards the addition and deletion of tasks. Leave detailed discussion to issues linked in tasks. If a task doesn't have an issue next to it, create one and leave a comment here so we can update the list.

* [ ] Official packages:
  * [x] CentOS (RPM)
  * [x] Debian (Apt)
  * [ ] OneGet (Windows)
  * [x] Homebrew
* [x] Windows installer (nsis or wix)
* [ ] Automatic upgrades
* [x] CI tests for Go v1.3+
* [x] Custom source tarball
  * Pre-built man pages 
  * Extra go file that specifies the current commit

**Comment by technoweenie** [comment]
I published the v0.5.4 packages to https://packagecloud.io/github/git-lfs. I'm going to try releasing all of the packages created by `docker/run_dockers.bsh` starting with the next release

**Comment by technoweenie** [comment]
As of v0.6.0, we have a windows installer, and CI tests for Go 1.3, 1.4.2, and 1.5.

**Comment by technoweenie** [comment]
All done here except automatic upgrades, which is going into the roadmap in #1438.
