### ISSUE TITLE
Release v1.0.0

### ISSUE THREAD

**Issue by technoweenie** [github/git-lfs#653]
* [x] fix usage to show 'git lfs' and missing `pull` flags #661
* [x] Fix `git lfs ls-files` when run from an empty repo #668 #669
* [x] Built-in docs use man pages #665 #670 
* [x] `update` and `init` commands can install the pre-push hook in bare repos #671
* [x] Add `GIT_LFS_SKIP_SMUDGE` and `init --skip-smudge` #679 
* [x] Fix `ls-files` with duplicate files #681 @Aorjoa @technoweenie

**Comment by sinbad** [comment]
I'm half way through purge but on polish terms I'd like to get `git-lfs <command> --help` / `git lfs help <command>` actually showing the proper man pages, it's becoming confusing for people to find the docs especially on Windows.

**Comment by sinbad** [comment]
My first attempt at that, much prettying that can be done: https://github.com/github/git-lfs/pull/665
