### ISSUE TITLE
Git LFS v1.0.1

### ISSUE THREAD

**Issue by technoweenie** [github/git-lfs#705]
We'll probably be shipping a v1.0.1:

* [x] Downcase git config keys (prevents Auth loop) https://github.com/github/git-lfs/pull/690
* [x] Show more info for unexpected http responses https://github.com/github/git-lfs/pull/710
* [x] Use separate stdout/stderr buffers for `git-lfs-authenticate` https://github.com/github/git-lfs/pull/718
* [x] Use LoggedError instead of Panic if update-index fails in checkout #735
* [x] `smudge` command exits with non-zero if the download fails #732
* [x] Use `git rev-parse` to find the git working dir #692 
* [x] Improved default remote behaviour & validation for fetch/pull #713
* [x] Make fetch return error code when 1+ downloads failed #734
* [x] Improve lfs.InRepo() detection in `init`/`update` #756
* [x] whitelist the valid keys read from .gitconfig #760
* [x] Teach smudge to use the batch api #711
* [x] Fix not setting global attribute when needed to b/c of local state #765
* [x] Fix clone fail when fetch is excluded globally #770 
* [x] Fix for partial downloads problem #763

## Investigate

* [ ] Detect when credential cacher is not setup #523 
* [ ] Fix issue with ssh shorthands #278 
* [ ] Dynamic size cutoff for blob scanning #524 
* [ ] git-lfs staged but unstaged changes with 0B tracked file #557 
* [ ] fetch/pull don't respect tracking graph #660
* [ ] pushing to a new remote fails if local storage isn't full #662

**Comment by sinbad** [comment]
> fetch/pull don't respect tracking graph #660

They actually do, the actual issue is that the error message isn't nice if the current checkout isn't on a tracking branch **and** there isn't an origin remote. Seems this is the case with a Jenkins build (and maybe other CIs). Alternative behaviour might be to use *any single* remote if origin isn't defined, i.e. if there's no origin and only one remote, use that, fail with nicer error if there's >1 remote and no origin.

**Comment by technoweenie** [comment]
Ah right, that was just cargo culted from the previous issue.
