### ISSUE TITLE
Git LFS v1.1

### ISSUE THREAD

**Issue by technoweenie** [github/git-lfs#755]
### Features

* [x] NTLM auth support https://github.com/github/git-lfs/pull/820 (@WillHipschman, @technoweenie)
* [x] `prune` command https://github.com/github/git-lfs/pull/742 (@sinbad)
* [ ] zsh auto completion https://github.com/github/git-lfs/pull/727
* [ ] netrc support https://github.com/github/git-lfs/pull/715
* [x] Use .lfsconfig instead of .gitconfig https://github.com/github/git-lfs/pull/837 (@technoweenie)
* [x] Rename "init" command https://github.com/github/git-lfs/pull/838 (@technoweenie)
* [ ] Better SSH remote handling #295 #278
* [x] Add more GIT_TRACE details: was auth sent? also, log http response bodies
* [x] Support git repos in symlinked directories https://github.com/github/git-lfs/pull/818 (@sinbad, @difro, @jiangxin)
* [x] Fix "git lfs env" to show correct SSH remote info #828 (@jiangxin)

### Refactoring

* [ ] Refactor readGitConfig() #777

### Investigate

* [ ] Refactor local storage #778
* [ ] Refactor API client #779
