### ISSUE TITLE
Git LFS v1.1.1

### ISSUE THREAD

**Issue by technoweenie** [github/git-lfs#967]
## Features

* [x] Add copy-on-write support for Linux BTRFS filesystem #952 (@bozaro)
* [x] convert `git://` remotes to LFS servers automatically #964 (@technoweenie)
* [x] Fix `git lfs track` handling of absolute paths. #975  (@technoweenie)
* [x] Allow tunable http client timeouts #977 (@technoweenie)

## Bugs

* [x] Suppress git config warnings for non-LFS keys #861 (@technoweenie)
* [x] Fix fallthrough when `git-lfs-authenticate` returns an error #909 (@sinbad)
* [x] Fix progress bar issue #883 (@pokehanai)
* [x] Support `remote.name.pushurl` config #949 (@sinbad)
* [x] Fix handling of `GIT_DIR` and `GIT_WORK_TREE` #963, #971 (@technoweenie)
* [x] Fix handling of zero length files #966 (@nathanhi)
* [x] Guard against invalid remotes passed to `push` and `pre-push` #974 (@technoweenie)
* [x] Fix race condition in `git lfs pull` #972 (@technoweenie)

## Extra

* [x] Add server API test tool #868 (@sinbad)
* [x] Redo windows installer with innosetup #875 (@strich)
* [x] Pre-built packages are built with Go v1.5.3

**Comment by technoweenie** [comment]
This "small" release turned out a bit bigger than I planned. But these are all good bug fixes:

https://github.com/github/git-lfs/releases/tag/v1.1.1

/cc @github/desktop
